# Generated by Django 3.2 on 2023-11-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(max_length=20)),
                ('approval_required', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing', to='api.todo')),
            ],
        ),
    ]
