# Generated by Django 3.2 on 2023-11-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todochangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todochangelog',
            name='approved_by_owner',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
