# Generated by Django 3.2 on 2023-11-30 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='todo_sharing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.todosharing'),
        ),
    ]
